"""Parsing of all three endpoint shapes against synthetic fixtures.

These fixtures are generated by tests/fixtures/make_fixtures.py, signed by
a reproducible throwaway fixture key (no real did:key identity involved).
Structural shape only -- live-shape fidelity is the live smoke test's job.
"""

from helpers import load_fixture


def test_rooms_overview_shape():
    d = load_fixture("rooms_overview.fixture.json")
    assert set(d.keys()) >= {"rooms", "total", "capacity", "bytes", "engagement"}
    assert isinstance(d["rooms"], list) and len(d["rooms"]) > 0

    room = d["rooms"][0]
    for key in ("room", "last_seq", "bytes", "idle_seconds", "topic"):
        assert key in room

    eng = d["engagement"]
    for key in ("zero_response_share", "nick_diversity", "windowed_messages"):
        assert key in eng


def test_events_log_page_shape():
    d = load_fixture("events_page.fixture.json")
    assert d["room"] == "events"
    for key in ("count", "first_seq", "last_seq", "generation", "messages"):
        assert key in d
    assert d["count"] == len(d["messages"])

    m = d["messages"][0]
    assert m["from"] == "server"
    assert m["text"].startswith("created ")
    assert "seq" in m and "ts" in m


def test_room_message_page_shape():
    d = load_fixture("lobby_page.fixture.json")
    assert d["room"] == "lobby"
    for key in ("count", "first_seq", "last_seq", "generation", "messages"):
        assert key in d
    assert d["count"] == len(d["messages"])
    assert d["last_seq"] >= d["first_seq"]

    signed = next(m for m in d["messages"] if "sig" in m)
    for key in ("seq", "ts", "from", "text", "nonce", "sig"):
        assert key in signed
    assert signed["from"].startswith("did:key:")


def test_room_message_page_second_room():
    d = load_fixture("meta_page.fixture.json")
    assert d["room"] == "meta"
    assert d["count"] == len(d["messages"])
    for m in d["messages"]:
        assert isinstance(m["seq"], int)
        assert isinstance(m["from"], str)


def test_unsigned_nick_message_has_no_nonce_or_sig():
    d = load_fixture("unsigned_nick_page.fixture.json")
    unsigned = [m for m in d["messages"] if "sig" not in m]
    signed = [m for m in d["messages"] if "sig" in m]
    assert len(unsigned) == 1
    assert len(signed) == 1
    assert not unsigned[0]["from"].startswith("did:key:")
    assert signed[0]["from"].startswith("did:key:")
    assert "nonce" not in unsigned[0]


def test_lobby_fixture_also_carries_two_unsigned_nicks():
    # The main lobby fixture separately covers unsigned-nick parsing
    # alongside signed writers in the same page, matching the real shape
    # (a room's stream mixes both kinds of `from`).
    d = load_fixture("lobby_page.fixture.json")
    unsigned = [m for m in d["messages"] if "sig" not in m]
    assert len(unsigned) == 2
    assert all(not m["from"].startswith("did:key:") for m in unsigned)
    assert all("nonce" not in m for m in unsigned)
